#! /usr/bin/env python3

import argparse
import logging

from genesys.client import GenesysSerialClient, GenesysTcpClient
from genesys.protocol import GenesysError

CMD = {"ADR", "CLS", "RST", "RMT", "RMT?", "MDAV?", "MS?", "IDN?", "REV?",
       "SN?", "DATE?", "PV", "PV?", "MV?", "PC", "PC?", "MC?", "MODE?", "DVC?",
       "STT?", "FILTER", "FILTER?", "OUT", "OUT?", "FLD", "FLD?", "FBD", "FBD?",
       "FBDRST", "OVP", "OVP?", "OVM", "UVL", "UVL?", "AST", "AST?", "SAV", "RCL"}

if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                     description="GENESYS command-line option",
                                     epilog="Usage example:\n"
                                            "genesys-console --method SERIAL --address COM1 --baudrate 9600 --send ADR 1\n"
                                            "genesys-console --method TCP --address '192.168.1.2:5000' --send ADR 1\n")

    parser.add_argument("--method", type=str, choices=["SERIAL", "TCP"],
                                    required=True, help="factory method")
    parser.add_argument("--address", type=str, required=True,
                                     help="serial port or IP:PORT")
    parser.add_argument("--baudrate", type=int, choices=[1200, 2400, 4800, 9600, 19200],
                                      default=9600, help="port baudrate (for SERIAL method)")
    parser.add_argument("--timeout", type=float, default=1.0,
                                     help="timeout in seconds")
    parser.add_argument("--debug", action="store_true",
                                   help="print debug information")
    parser.add_argument("--send", type=str, nargs="+", metavar=("CMD", "VALUE"),
                                  required=True, help="send CMD with value")
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    if args.method == "SERIAL":
        client = GenesysSerialClient(address=args.address, baudrate=args.baudrate, timeout=args.timeout)
    elif args.method == "TCP":
        client = GenesysTcpClient(address=args.address, timeout=args.timeout)

    if args.send:
        cmd = args.send[0]
        if cmd.upper() not in CMD:
            msg = f"Unknown command {cmd}"
            raise GenesysError(msg)
        try:
            value = args.send[1]
        except IndexError:
            value = None

        print(client._send(cmd, value))
